export { get, post, patch, del, ApiError } from './client';
export { fetchTeams, fetchTeam } from './teams';
export type { Team, TeamDetail, TeamStanding, MatchSummary } from './teams';
export { fetchMatches, fetchMatch } from './matches';
export type { Match, MatchEvent, MatchStat, MatchFilters } from './matches';
export { fetchMe, createUser, updateTeam, updatePreferences, updatePushSubscription, deletePushSubscription } from './users';
export type { UserProfile, CreateUserData, PushSubscriptionData } from './users';
export { getVapidPublicKey } from './push';
export type { VapidPublicKey } from './push';
export { qk, staleMs } from './queryKeys';
